
/**
 * Cliente Supabase
 * 
 * Este arquivo configura e exporta o cliente Supabase para ser usado em toda a aplicação.
 * O cliente permite interagir com a autenticação, banco de dados e armazenamento do Supabase.
 * 
 * @module integrations/supabase/client
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuração de acesso ao Supabase
const SUPABASE_URL = "https://vkzbcqdjvcggscmkbldz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZremJjcWRqdmNnZ3NjbWtibGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjEwMzgsImV4cCI6MjA2MTU5NzAzOH0.WLrpYtEvQuWcDnaK-WQyBLTMfBrqMzJaBGgBV8murvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
